### ISSUE TITLE
Error on very large views

### ISSUE THREAD

**Issue by bkw** [iriscouch/couchjs#1]
While trying couchjs with a replica of the npm database, I get consistent crashes due to parsing an incomplete json buffer:

```
Error 19988: SyntaxError: Unexpected end of input at Object.parse (native)
    at Loop (eval at <anonymous> (/usr/local/lib/node_modules/couchjs/cli.js:67:21))
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/couchjs/cli.js:67:21))
```

/tmp/couchjs.log shows the rest of the json coming in as separate lines on stdin (actually 25 of them).

I haven't wrapped my head around fibers yet, so I can't really offer a fix (for what I suspect to be couchjs.readline). Happy to supply more input though.

**Comment by bkw** [comment]
I put the couchjs.log here: https://gist.github.com/4648302

**Comment by bkw** [comment]
Sorry, I forgot to say that happened with the couchjs version currently up at npmjs.org.

I just tried the git master and it works. Sweeet!
New release?

**Comment by jhs** [comment]
Yes, time for a release.
